"""
Markdown Export Module.

Formats the final research report as a clean .md file
with metadata header and saves to the reports directory.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from backend.config import settings

logger = logging.getLogger(__name__)


def export_markdown(
    session_data: dict,
    output_dir: Optional[Path] = None,
) -> Path:
    """
    Export a research session's report as a Markdown file.

    Parameters
    ----------
    session_data : dict
        Complete session data with 'final_report', 'user_query', etc.
    output_dir : Path, optional
        Directory to save the file. Defaults to settings.REPORTS_DIR.

    Returns
    -------
    Path
        Path to the generated Markdown file.
    """
    output_dir = output_dir or settings.REPORTS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    session_id = session_data.get("session_id", "unknown")
    query = session_data.get("user_query", "Research")
    report = session_data.get("final_report", "No report available.")
    created_at = session_data.get(
        "created_at", datetime.now(timezone.utc).isoformat()
    )
    sources = session_data.get("sources", [])

    # Create a clean filename from the query
    safe_query = "".join(
        c if c.isalnum() or c in (" ", "-", "_") else "_"
        for c in query[:50]
    ).strip().replace(" ", "_")

    filename = f"{safe_query}_{session_id[:8]}.md"
    filepath = output_dir / filename

    # Build the markdown content
    md_content = f"""---
title: "{query}"
session_id: "{session_id}"
generated_at: "{created_at}"
sources_count: {len(sources)}
generator: "AI Research Assistant"
---

{report}

---

*This report was generated by the AI Research Assistant.*
*Session ID: {session_id}*
*Generated: {created_at}*
"""

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md_content)
        logger.info(f"Markdown report exported to: {filepath}")
        return filepath
    except Exception as e:
        logger.error(f"Failed to export Markdown: {e}")
        raise


def get_markdown_content(session_data: dict) -> str:
    """
    Get the Markdown content as a string (for download without saving).

    Parameters
    ----------
    session_data : dict
        Complete session data.

    Returns
    -------
    str
        Formatted Markdown content.
    """
    query = session_data.get("user_query", "Research")
    report = session_data.get("final_report", "No report available.")
    session_id = session_data.get("session_id", "unknown")
    created_at = session_data.get(
        "created_at", datetime.now(timezone.utc).isoformat()
    )
    sources = session_data.get("sources", [])

    return f"""---
title: "{query}"
session_id: "{session_id}"
generated_at: "{created_at}"
sources_count: {len(sources)}
---

{report}

---
*Generated by AI Research Assistant | Session: {session_id}*
"""
