"""
LangGraph state schema for the research workflow.

Uses TypedDict with Annotated reducers so that log entries
accumulate across nodes rather than being overwritten.
"""

from __future__ import annotations

import operator
from typing import Annotated, TypedDict


class ResearchState(TypedDict, total=False):
    """
    Shared state flowing through every node of the LangGraph workflow.

    Fields
    ------
    user_query : str
        The original research topic entered by the user.
    research_plan : dict
        Structured plan produced by the Planner node.
        Contains 'objectives', 'sub_topics', and 'search_queries'.
    search_results : list[dict]
        Raw search hits from DuckDuckGo and Wikipedia.
        Each dict has 'title', 'url', 'snippet', 'source'.
    sources : list[dict]
        Deduplicated and enriched source metadata.
    insights : list[str]
        Key findings extracted by the Analysis node.
    summary : str
        Executive summary generated by the Summary node.
    final_report : str
        Full markdown report with citations from the Report node.
    memory : dict
        Session metadata (id, timestamp, status).
    logs : Annotated[list[str], operator.add]
        Execution log entries — accumulated across all nodes.
    model : str
        The LLM model identifier being used for this run.
    session_id : str
        Unique identifier for this research session.
    """

    user_query: str
    research_plan: dict
    search_results: list[dict]
    sources: list[dict]
    insights: list[str]
    summary: str
    final_report: str
    memory: dict
    logs: Annotated[list[str], operator.add]
    model: str
    session_id: str
